### ISSUE TITLE
Support for grunt >= 1.0.0

### ISSUE THREAD

**Issue by piechu** [dpellier/compare-json#4]
As I can see update made in package.json to support new grunt version - could you release new version of plugin?

Currently available version 0.1.1 has still grunt peer dependency set to ~0.4.1.

**Comment by dpellier** [comment]
The dev dependency has been changed to `>=0.4.1` in here https://github.com/dpellier/compare-json/pull/5
So you should be fine using grunt 1.0.
(you may see some WARN about other package, just ignore them)
